version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URI=mysql+pymysql://root:password@db:3306/theory_db
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: always

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=theory_db
    ports:
      - "3306:3306"
    restart: always

volumes:
  db_data: